FROM php:8.2-apache

# Instala as extensões do PHP necessárias para o MySQL
RUN docker-php-ext-install pdo pdo_mysql mysqli

# Copia o código-fonte do projeto para o diretório do Apache
COPY . /var/www/html/

# Dá permissão ao diretório HTML
RUN chown -R www-data:www-data /var/www/html/

# Expondo a porta 80 (Apache)
EXPOSE 80
